### ISSUE TITLE
Support for campexplorer.io

### ISSUE THREAD

**Issue by Nzzyme** [cvzi/Bandcamp-script-deluxe-edition#1]
Hello,

Thanks for this wonderful script. I am the original requester of this script on openuserjs.org

I was wondering if you are able to also support this website: https://campexplorer.io/

This is basically a service that can search Bandcamp using genres and display the search results as seen here (https://i.imgur.com/jky3nN5.png)

Can you make a tweak to your script so that on the search results, we are directly able to click on the play button of an album and the track begins to play at the bottom of the page just like it currently does on Bandcamp album page shown here (https://i.imgur.com/FIWP3sy.jpg)

Thanks

**Comment by cvzi** [comment]
I'll check it out. Should be easy to do

**Comment by cvzi** [comment]
This was almost too simple, let's hope it actually works.

... and thanks for introducing me to this website, it's actually really cool with the script 😁

**Comment by Nzzyme** [comment]
Works like a charm. Thank you so much. Appreciate it. 🤝

**Comment by Nzzyme** [comment]
Could you please check playback on campexplorer.io I am unable to play the tracks by clicking on the albums? Thanks

**Comment by cvzi** [comment]
It works for me. Could you check if it was only a temporary problem or if it still does not work for you

**Comment by Nzzyme** [comment]
Hi, thanks for looking. I checked again and can confirm that I am unable to play. It is worth mentioning that I am now on Windows 7 temporarily and checking in Chrome browser with the latest version of your script.

![image](https://user-images.githubusercontent.com/6959116/101271754-c2ad3a80-37ab-11eb-8ee5-55ba7996078c.png)

**Comment by cvzi** [comment]
Could you check in the developer console of Chrome if there is an error?

Go to campexplorer then in Chrome click on ![dots](https://storage.googleapis.com/support-forums-api/attachment/thread-1873663-11570270203781843251.png) then **More tools** > **Developer tools** go to the **Console** tab
Press Ctrl + L to clear the console. Now try to play an album and see if something appears in the console.
You can try the same with the search results on bandcamp.

**Comment by Nzzyme** [comment]
I followed the steps you provided. Here is what I see. Hope this helps

![image](https://user-images.githubusercontent.com/6959116/101279444-4e44bc80-37e8-11eb-84fa-4488d1923989.png)

**Comment by cvzi** [comment]
The error means, that the script cannot download/access the album page (in this example https://darkestgrove.bandcamp.com/album/pain-and-suffering-shall-be-known ). 

I am clueless why that is happening. 

Could you do the steps again, and then press the little triangles next to the red text to expand the error messages. I am interested in the part between the curly brackets `Function { readyState: 4, .....}`

**Comment by Nzzyme** [comment]
Sure, here you go:

![image](https://user-images.githubusercontent.com/6959116/101282235-eb5c2100-37f9-11eb-9edc-24444e01b7a9.png)
![image](https://user-images.githubusercontent.com/6959116/101282242-f7e07980-37f9-11eb-837e-426f803a1d5e.png)

**Comment by cvzi** [comment]
Thank you.
It looks like either Chrome or Tampermonkey are blocking the request to the album page. I still don't understand why though.

**Comment by Nzzyme** [comment]
Hmm, I initially suspected it to be the adblock extensions that I use (uBlock Origin / AdGuard) but I actually disabled them and had checked them before providing you with the last results. Anyway, for now, atleast I can navigate to the album page and play it from there. So, we'll keep an eye on this one for a later fix.

I will be buying an SSD soon and will be clean installing Windows 10 later. So, will check then and let you know if this issue still persists then.

Thanks!

**Comment by cvzi** [comment]
The only progress I made so far is that I can create the same error message, when I turn off my wifi/internet connection before trying to play an album. But that doesn't really help me to understand it.

Have you tried a fresh install of the userscript? (You can disable the current one and change its name in the source code in Tampermoneky, so you don't lose the current script and its data, then you can install a fresh copy)

**Comment by Nzzyme** [comment]
As I had guessed, there seems to be some issue with my Chrome browser. I tried your latest version with Firefox and it works fine on this site.
