### ISSUE TITLE
[Suggestion] Play from Search Results

### ISSUE THREAD

**Issue by Nzzyme** [cvzi/Bandcamp-script-deluxe-edition#19]
Hi, I was wondering if you could add a feature to your amazing script which would allow us to play the tracks by clicking on the album art of an album after performing a search.

The play icon can be visible on the art work of tracks, albums and artists not for artist.

Example: https://bandcamp.com/search?q=lounge%20music

The functionality could be similar to the playback on the discography pages (player coming up at the bottom of the page). Is this feasible?

**Comment by cvzi** [comment]
Seems to work (:

**Comment by Nzzyme** [comment]
I checked now and some albums do not work when I click on them from the search results

![image](https://user-images.githubusercontent.com/6959116/101271796-20da1d80-37ac-11eb-8e10-410a5cdf1d40.png)

**Comment by Nzzyme** [comment]
I checked again with Firefox and the latest version (1.17.0) and it works perfectly when playing from the search results. Thanks for implementing this.

**Comment by Nzzyme** [comment]
Hello,

I was trying to play few albums directly from the search results but was unable to in Chrome. Can you please check?

Just open bandcamp.com and perform any search and try to play directly from the results.

**Comment by cvzi** [comment]
I have updated it

Something is currently wrong at openuserjs.org and I can't upload the new version there.
The new version is on https://greasyfork.org/en/scripts/390404-bandcamp-script-deluxe-edition

**Comment by Nzzyme** [comment]
I re-installed the version from the greasyfork link but still unable to play from the search results. I am using Chrome on Win 7

**Comment by cvzi** [comment]
I think it didn't update the script on greasyfork either. (The new version is 1.18.11)
It is up to date on both sites now, so you should automatically receive the update.

**Comment by Nzzyme** [comment]
Yes, it is updated now and it works fine. Thank you
