### ISSUE TITLE
Add support for site

### ISSUE THREAD

**Issue by Nzzyme** [cvzi/Bandcamp-script-deluxe-edition#207]
Hello, can you please add the following site to the list as the script currently does not work with this site.

https://3six.net/music

**Comment by cvzi** [comment]
I get an immediate redirect to https://3six.bandcamp.com/music when I try to open https://3six.net/music

**Comment by Nzzyme** [comment]
> I get an immediate redirect to https://3six.bandcamp.com/music when I try to open https://3six.net/music

Hmm, it does not redirect for me, I am not sure why. Must be the OS / browser / etc. Checked again after disabling other extensions. Anyway, are you able to add this site to the list of supported sites?

**Comment by cvzi** [comment]
When you are on the site, can you click the tampermonkey icon and see in the menu if the script is running on the site and see if there is an entry "enable on this page" under "Bandcamp script (Deluxe Edition)"

**Comment by Nzzyme** [comment]
> When you are on the site, can you click the tampermonkey icon and see in the menu if the script is running on the site and see if there is an entry "enable on this page" under "Bandcamp script (Deluxe Edition)"

That did the trick. Thank you!!
