### ISSUE TITLE
Custom Player on Tag Search Pages

### ISSUE THREAD

**Issue by Nzzyme** [cvzi/Bandcamp-script-deluxe-edition#208]
With regards to the Tag search enhancement of the script as seen [here](https://github.com/cvzi/Bandcamp-script-deluxe-edition/issues/126#issue-1021987767), I wanted to check if you are able to let your custom player play the tracks after the tags are selected and the user clicks on the play icon on the album thumbnail?

Currently, when hitting play, the default Bandcamp player plays the track after a Tag search which is very limited as we are unable to skip to the next track.

Default BC Player: 
![image](https://user-images.githubusercontent.com/6959116/187699771-8b75b2af-cca9-4275-a4b2-54d02d9e7f6c.png)

Your custom player:
![image](https://user-images.githubusercontent.com/6959116/187699862-002362a6-e695-4e72-ab4b-972860bd341f.png)

Are you able to add the skip to next track arrow buttons to the player?

**Comment by cvzi** [comment]
I have added a first try

**Comment by Nzzyme** [comment]
> I have added a first try

Perfect. Tried and it works well! Thanks a lot!!

**Comment by Nzzyme** [comment]
Hi @cvzi Hope you are fine. I am not sure what changed but when I try to play tracks via a TAG search, it does not play via your custom player. It only plays via the default player as seen here: https://prnt.sc/KvvpQnZ9RPSd

I ensured that the relevant setting is checked (https://prnt.sc/-n1cfEG1Fbkk)

I am not on Windows 10. Can you please take a look

**Comment by cvzi** [comment]
It seems that the whole script is not loaded on the tag search sometimes. The script settings button doesn't appear and the script doesn't even show up in the Tampermonkey menu. 

I pressed F5 a few times and sometimes the script does run, sometimes not.

If the script is running, the player seems to work fine.

Very strange

**Comment by cvzi** [comment]
Can you try these steps from https://www.tampermonkey.net/faq.php#Q208 :

> To fix the issue simply:
> *  Disable Tampermonkey extension
> *  Restart Chrome (make sure that all browser processes are gone, better restart the computer)
> *  Enable Tampermonkey extension
> *  Restart Chrome

**Comment by Nzzyme** [comment]
> Can you try these steps from https://www.tampermonkey.net/faq.php#Q208 :
> 
> > To fix the issue simply:
> > 
> > * Disable Tampermonkey extension
> > * Restart Chrome (make sure that all browser processes are gone, better restart the computer)
> > * Enable Tampermonkey extension
> > * Restart Chrome

Thanks! I tried these steps and it worked for me.
