### ISSUE TITLE
Script Icons

### ISSUE THREAD

**Issue by Nzzyme** [cvzi/Bandcamp-script-deluxe-edition#278]
Hello, I observed that the script icons are truncated and not displayed completely.

![image](https://user-images.githubusercontent.com/6959116/235308780-47075aaa-439f-4992-affa-f26ee5adad50.png)

Can you please check? I am using latest Chrome version on 64 bit Windows 11.

Observed on the following page: https://monasteriumimperi.bandcamp.com/album/trichurch-of-katehon

Does not happen on all the pages though.

**Comment by cvzi** [comment]
The buttons come down if you hover the mouse over them. It didn't work correctly, now it should work again.
