### ISSUE TITLE
date format yyyy.mm.dd

### ISSUE THREAD

**Issue by stvv0000** [cvzi/Bandcamp-script-deluxe-edition#284]
can you please make option to show date on albums in yyyy.mm.dd format?

**Comment by cvzi** [comment]
Could you post a screenshot of where exactly?

**Comment by stvv0000** [comment]
![image](https://github.com/cvzi/Bandcamp-script-deluxe-edition/assets/131647018/50f5d1c9-a47f-4073-a43e-473c963f1cf4)

**Comment by cvzi** [comment]
Oh I understand. I'll add it when I have some time.

**Comment by stvv0000** [comment]
thank you very much!

**Comment by cvzi** [comment]
Format fields:
```
%isoDate%		 2001-02-03T00:00:00.000Z
%D%			 3
%DD%			 03
%Da%			 Sat
%Day%			 Saturday
%Dord%			 3rd
%M%			 2
%MM%			 02
%Mon%			 Feb
%Month%			 February
%YY%			 01
%YYYY%			 2001
%json%			 2001-02-03T00:00:00.000Z
%unix%			 981154800
```

**Comment by stvv0000** [comment]
it works, but not everywhere 
here won't work for some reason https://itsaso.bandcamp.com/album/a-s-o but on other albums for this artist everything is fine
maybe because it's pre-order?

**Comment by cvzi** [comment]
Yes pre-order was the problem, now it should work.
