### ISSUE TITLE
Wishlist individual songs from within the player

### ISSUE THREAD

**Issue by thalliumoxide** [cvzi/Bandcamp-script-deluxe-edition#285]
Absolutely in love with this script but I have one small gripe with it that could be improved. Being able to wishlist individual songs from within the player. I believe wishlisting a whole album when you only like one or two songs is rudimentary, so having the option to add individual songs to your wishlist would be so much faster.

**Comment by cvzi** [comment]
This should be simple to add.

However I see a problem: you cannot add all songs to the wishlist. It seems that only songs that can actually be bought individually can be added to wishlist.
I am not sure if this behavior can be detected without opening the track page, so potentially there would be a "Add track to whislist" button that does nothing for some tracks.

**Comment by cvzi** [comment]
Implemented in v1.26.0
The tracks that can be added to the wishlist should have a "Add song" button in the player.

(it might not immediately work for albums/songs that you already played, because the player has a cache function)
