### ISSUE TITLE
download links on purchased album pages

### ISSUE THREAD

**Issue by stvv0000** [cvzi/Bandcamp-script-deluxe-edition#288]
btw it is possible to add somewhere here(pic 1) or here(pic 2) link to download album? its strange why bandcamp hasn't done it themselves yet
![image](https://github.com/cvzi/Bandcamp-script-deluxe-edition/assets/131647018/837a665e-1b8b-4f4c-ba50-baf2fd10f4a3)

**Comment by cvzi** [comment]
I am not sure. I haven't looked at how to generate download links.

**Comment by cvzi** [comment]
I started to implement this: For now it only works for the albums that appear on the https://bandcamp.com/{username}/purchases page when you open the page. So only the most recent purchases work.  

I leave this issue open, maybe I'll find the energy to make it work for older purchases as well
