### ISSUE TITLE
Would it be possible to display the "player" on the "Album" page as well?

### ISSUE THREAD

**Issue by 2-3-5-7** [cvzi/Bandcamp-script-deluxe-edition#292]
Would it be possible to display the "player" on the "Album" page as well, since some creators only have one album and no "Discography" page. 
For example, https://flowerstorm.bandcamp.com/ will automatically redirect to https://flowerstorm.bandcamp.com/album/yek and thus not display the player.

**Comment by cvzi** [comment]
It is now possible to hover the mouse over the top right corner of the album art on the album page and then a play button appears

**Comment by 2-3-5-7** [comment]
Thanks, but there's a small problem. I can see it in Chrome, but not on Firefox for the play button.
