### ISSUE TITLE
The player on the album page is not functioning in Firefox

### ISSUE THREAD

**Issue by 2-3-5-7** [cvzi/Bandcamp-script-deluxe-edition#297]
Thank you for supporting the player on the album page. It works fine on Chrome, but the play button is not showing up on Firefox.

**Comment by cvzi** [comment]
Could you please check in the error console if an error occurs?

Go to an album page and press F12, then go to the "console" tab, on the right only select "errors" and unselect "warnings", "logs", ....
Then press the little trash 🗑️ button to clear everything. 
Press F5 and then move the mouse over the album art. 
See if any errors appear in the console.

**Comment by 2-3-5-7** [comment]
Now it's working properly, not sure why. Earlier, I couldn't see the play button even after clearing the website cache and using private mode. 
Perhaps there is no issue now.🤔
