### ISSUE TITLE
Support Shop Pages

### ISSUE THREAD

**Issue by Nzzyme** [cvzi/Bandcamp-script-deluxe-edition#3]
Hello, can you please tweak your script to also support 'shop' pages which lists albums like this one:

https://shop.stereoscenic.com/music

Thanks

**Comment by cvzi** [comment]
Do you happen to know other "shop" pages?
The URL of these shops does not contain bandcamp.com. Currently the script only runs on *.bandcamp.com URLs (and campexplorer.io). To support shops, the script will need to run on all URLs.
That means I need to find a robust way to identify if a website is actually a bandcamp shop or not. It would be helpful to have more examples to test that.

**Comment by Nzzyme** [comment]
You are right. I don't think that shop page was a bandcamp one. For now, I think we can close this one. I will post another request about a possible dark theme on bandcamp, an idea which I have been having in my mind since sometime.

**Comment by cvzi** [comment]
I think it just doesn't have a bandcamp URL. I believe music labels can create these shops on bandcamp and then somehow put them on their own website to showcase.

I know I have seen several of these in the past, but I cannot remember any.

When I stumble upon another one, I will try to make it work. I just doesn't make sense to make it work for this one, when I don't know how different the next one could be.

**Comment by cvzi** [comment]
I found a few other shops.
The script now runs on all sites. If it is probably a shop page, the script will ask if it should run or not.

**Comment by Nzzyme** [comment]
Perfect. I'll keep an eye for shop pages and let you know if I find any where the script did not detect it.

**Comment by cvzi** [comment]
The opposite could also happen, that the window pops up on pages that are not shop pages
