### ISSUE TITLE
/feed auto play next album ?

### ISSUE THREAD

**Issue by freeload101** [cvzi/Bandcamp-script-deluxe-edition#311]
Was it just me or did /feed play the next item in the list?

![image](https://github.com/cvzi/Bandcamp-script-deluxe-edition/assets/4307863/e25487c3-f448-4d5a-8a1a-b5aa7dd3ffd3)

**Comment by cvzi** [comment]
I don't know if it used to to it, I don't use the feed very often myself.

I guess it can be added easily.
Do you mean playing the next item of the feed or the next track of the album?

**Comment by freeload101** [comment]
next Album would be cool. Or how do you discover new music ?

**Comment by cvzi** [comment]
I mostly search for tags, although I did use the feed in the past. Maybe I just forget how useful the feed actually is 😂

I'll add both:
 * when the playback ends, the next item/album from the feed is played
 * a separate button to play the whole album in the script's own "discography player"
