### ISSUE TITLE
discography player doesn't appear

### ISSUE THREAD

**Issue by elfh78** [cvzi/Bandcamp-script-deluxe-edition#357]
discography player doesn't appear, but it is checked in settings. i use brave browser. otherwise great script!

**Comment by cvzi** [comment]
It still works for me in Chrome which shouldn't be too different from Brave. Maybe I can check Brave browser later.

**Comment by cvzi** [comment]
I did found some random artists where it doesn't work.

On these artist pages the "large album covers" don't work:
https://multiculti.bandcamp.com/music
https://100copies.bandcamp.com/music
https://hotbiscuitrecordings.bandcamp.com/music

Conversely on these artists pages they work:
https://chapelofdisease.bandcamp.com/music
https://endoraysusvicios.bandcamp.com/music

**Comment by elfh78** [comment]
i opened pages from both groups and don't have discography player on them

**Comment by cvzi** [comment]
What happens if you move the mouse over an album cover, does the "play"-arrow show up? 

And what happens if you click on an album cover, nothing or does it open the album page?

**Comment by elfh78** [comment]
play arrow appears and when i click script player shows up. now i think that i understood incorrectly previously and it works as expected, coz i didn't click before, i thought it should appear on the page instantly, when i open it.
