### ISSUE TITLE
Script hangs on an artist's album page when dark theme is enabled

### ISSUE THREAD

**Issue by afgks** [cvzi/Bandcamp-script-deluxe-edition#358]
It seems that the script hangs on this artist's album page when dark theme is enabled. Can be reproduced on different browsers.

https://feedingear.bandcamp.com/album/orwell-original-game-soundtrack
https://feedingear.bandcamp.com/album/basement-original-game-soundtrack

**Comment by cvzi** [comment]
I have released an update that should fix it
