### ISSUE TITLE
 Juke box mode everywhere?

### ISSUE THREAD

**Issue by freeload101** [cvzi/Bandcamp-script-deluxe-edition#360]
Juke box mode everywhere for search and feed ? :

https://bandcamp.com/rmccurdydotcom/feed
https://bandcamp.com/discover/electro-swing

name your price freeload101@GGEEMAIL.com

**Comment by cvzi** [comment]
Yes I am aware the new discover page is not working. I tried fixing it, but then Bandcamp changed something on the page again and immediately broke it again. So I decided to wait a bit in case they decide to keep changing things.
 
But I guess it has been over two months now, so I should try again. 
-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.

**Comment by freeload101** [comment]
> Yes I am aware the new discover page is not working. I tried fixing it, but then Bandcamp changed something on the page again and immediately broke it again. So I decided to wait a bit in case they decide to keep changing things. But I guess it has been over two months now, so I should try again. -- Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.

LMK https://outlook.office365.com/book/Mccurdy@Newellco.onmicrosoft.com to setup a call any time ! I would love to get some consulting for tampermonkey etc $$/hr ? .

**Comment by cvzi** [comment]
I only do Tampermonkey stuff as a hobby. Thanks for the Patreon donation!

I added the player to the new "Discover" page. Clicking an album cover opens the player. I left the small button in the lower left corner of the album covers intact, so bandcamp's own player still works as well.

In the feed: it still only works with the small "play album"-link next to the "buy now" and "wishlist" links. I think I'll add it to the album covers in the feed as well though. Maybe a play-icon in the upper right corner of the album.

**Comment by cvzi** [comment]
Already found a problem 😂 
When the script's player is playing music and you click on bandcamp's play-button then the bandcamp player starts playing music, but the script player doesn't pause its music, so both play simultaneously. Same problem other way round.

**Comment by freeload101** [comment]
> Already found a problem 😂 When the script's player is playing music and you click on bandcamp's play-button then the bandcamp player starts playing music, but the script player doesn't pause its music, so both play simultaneously. Same problem other way round.

I can work around that discovery does not work but if I goto a lables entire album it does ?!:


https://github.com/cvzi/Bandcamp-script-deluxe-edition/assets/4307863/83946cb0-7fd3-4032-95ee-fddf9d8dbb9a

**Comment by cvzi** [comment]
Thanks, yeah I get it now. And yes you are right, it is similar to the label page and it should be easy to add the scraping functionality. I assumed this would just work once the player is active on the page and forgot to test it.

**Comment by cvzi** [comment]
I made some changes, not sure if this was enough. Didn't have much time, but it seemed to work on feed and discover on first glance.

**Comment by cvzi** [comment]
I added another feature: It is now possible to drag'n'drop album links or urls into the playlist to add them. Basically any link that contains /album/ or /track/

For example you could drag the url bar from another tab into the playlist or just normal links to Bandcamp albums.
Also you can select multiple albums by "text selecting" them and then dragging the selected text into the playlist (from another tab). 

Dragging just album covers doesn't work at the moment, since they don't contain the url to the album, but I think I can fix that in the future.
Discography pages a.k.a. labels or "Music" urls with multiple albums on them don't work either.

**Comment by freeload101** [comment]
> I added another feature: It is now possible to drag'n'drop album links or urls into the playlist to add them. Basically any link that contains /album/ or /track/
> 
> For example you could drag the url bar from another tab into the playlist or just normal links to Bandcamp albums. Also you can select multiple albums by "text selecting" them and then dragging the selected text into the playlist (from another tab).
> 
> Dragging just album covers doesn't work at the moment, since they don't contain the url to the album, but I think I can fix that in the future. Discography pages a.k.a. labels or "Music" urls with multiple albums on them don't work either.

![image](https://github.com/cvzi/Bandcamp-script-deluxe-edition/assets/4307863/16c58146-5e14-44e7-bfed-e9037d0639bc)
