### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by Nzzyme** [cvzi/Bandcamp-script-deluxe-edition#4]
As mentioned earlier in my last issue, are you able to include a dark theme in your awesome script that will support all domains and sub-domains of bandcamp? It can be included in settings with an option to enable / disable it. I think it is already implemented in another script (https://userstyles.org/styles/browse/bandcamp)

**Comment by cvzi** [comment]
I'll check it out.

**Comment by cvzi** [comment]
I tested the ones on userstyles.org and I think this one looks best:
https://userstyles.org/styles/171538/bandcamp-in-dark

I will see how to include it and what else can be made dark.  Any suggestions? I am not very good with design 😂

**Comment by Nzzyme** [comment]
Sorry for the late reply. I think that will do for now. If some elements are not displayed correctly, we will fix them later. Thank you!

**Comment by cvzi** [comment]
Dark mode is now in the settings. I know you have an older Windows, so if it looks very bad, post some screenshots. I only tested Windows 10 (and Ubuntu 20.04)

**Comment by Nzzyme** [comment]
Thanks for implementing the dark mode. I did a few checks with and without the setting enabled and found that it works well with one minor exception.

https://jimbutler.bandcamp.com/music

Screenshot of the page without dark mode  https://i.imgur.com/fRYj0Wl.jpg  You will see that the panes on the right and left have a design.

However, the same page with the dark mode enabled https://i.imgur.com/oW0HswT.png. It darkens the entire area on the right, left and center of the page.

Are you able to tweak your script so that only the center area of the page (near the album art images) is dark? (like the ones shown here: https://i.imgur.com/QPb9COm.jpg)

Thanks once again for implementing this.

**Comment by cvzi** [comment]
It would be best to keep the background design, but make the design darker if it is a bright design. I have an idea that it should be possible. If not I'll just restore the background design and only darken the center area.

I am going to add an option to switch between normal and dark theme based on the time. I just don't like it in the daylight 😁
