### ISSUE TITLE
Settings Icon Missing

### ISSUE THREAD

**Issue by Nzzyme** [cvzi/Bandcamp-script-deluxe-edition#5]
Hi, I just observed that the settings icon of your script is missing on some of the discography & album pages of BC.

Discography Page: https://maxcorbacho.bandcamp.com/music
Album Page: https://maxcorbacho.bandcamp.com/album/ars-lucis
Screenshot (Discography Page): https://i.imgur.com/dWcwqCo.png
Screenshot (Album Page): https://i.imgur.com/mt4Dtm9.png

For other discography pages, I am able to see the Settings icon.

Ex: https://wildearthvoices.bandcamp.com/music
Screenshot: https://i.imgur.com/5XRydsy.png

Can you please check and fix this? Thanks

**Comment by cvzi** [comment]
These pages are missing the "normal" bandcamp "bar"
In the HTML source on the pages, it actually says:
```<div id="customHeaderWrapper"><map name="_bc_customheader_map" id="_bc_customheader_map">....```
If they are custom, they are probably different on other pages. 

I'll just put the icon somewhere

**Comment by Nzzyme** [comment]
Thank you! Let me know once you fix this
