### ISSUE TITLE
Play/Pause Icon Transition

### ISSUE THREAD

**Issue by Nzzyme** [cvzi/Bandcamp-script-deluxe-edition#54]
Hello, hope you are fine. I am playing a track by clicking on the play icon on the album art. Now while the track is playing, if I move the mouse pointer (hover) over the same album art picture, the icon changes from pause icon to play icon. Ideally, it should be the opposite. That is, initially the icon should show the 'play' icon and when we click on that, it should change to 'Pause' icon and when we move the move pointer over that, it should remain as the paused icon so that we are able to pause it.

https://prnt.sc/1089qxa

Functionality wise, it works fine but just a small tweak is need to be visually correct.

**Comment by cvzi** [comment]
Clicking on the album cover now shows the correct state.

TODO: When clicking pause button in the player then it's still wrong

**Comment by Nzzyme** [comment]
Hello, did you get a chance to look into this one? When I click on the Play icon of an album art thumbnail (discography page), it does not transition to the Pause icon but remains unchanged.

Screenshot: https://prnt.sc/p7nMq2rgRXAy

**Comment by cvzi** [comment]
Should be fixed now
