### ISSUE TITLE
Add Timestamp to Player

### ISSUE THREAD

**Issue by Nzzyme** [cvzi/Bandcamp-script-deluxe-edition#55]
Hi, are you able to add a timestamp to your player? I noticed this is not currently available. It is available in the default BC player. See screenshots

Your Player: https://prnt.sc/108a9ev

Default Player: https://prnt.sc/108a9rc

**Comment by cvzi** [comment]
It was already there, but hidden because your screen seems to be narrower than mine
Layout/design is not my thing 😂

**Comment by Nzzyme** [comment]
Thanks, I am now able to see it

https://prnt.sc/1093rf3
