### ISSUE TITLE
Question About Album Backup/Restore

### ISSUE THREAD

**Issue by sproclavism** [cvzi/Bandcamp-script-deluxe-edition#6]
If I have an export file and use it to restore, will it overwrite the current data, or just add on top of it?

Thanks

**Comment by cvzi** [comment]
It combines the current data and the backup data. 
Generally, this means adding on top.
The exception: If you have clicked "played" twice to set an album "played" and then "Unplayed" again, it will overwrite that album.

**I have not tested this backup behavior yet.**
If you want to make sure, make a backup of your current data as well, and if something went wrong, we could combine the two backup files manually.

**Comment by sproclavism** [comment]
Okay, thanks for getting back to me. I will have a look. :+1:
