### ISSUE TITLE
Not working on Album pages?

### ISSUE THREAD

**Issue by Nzzyme** [cvzi/Bandcamp-script-deluxe-edition#7]
Hello, hope you are fine. I was trying to play some music on the following page and observed that the play icon no longer appears on the album art and clicking on the album art does not show the player at the bottom of the page. Can you please take a look? Thank you!

Example:
https://teramangalameditationmusic.bandcamp.com/music

Edit: I observed that it plays well on the following page

https://jimbutler.bandcamp.com/music

**Comment by cvzi** [comment]
I assume it's because the first link are single tracks and not albums, but I know it used to work for tracks as well. Probably they changed something in the page design

**Comment by cvzi** [comment]
New version is online

**Comment by Nzzyme** [comment]
Works fine now. Thank you and have a great day 👍
